basePath: /api/v1
definitions:
  modular-monolith_internal_modules_auth_domain.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  modular-monolith_internal_modules_auth_domain.LoginResponse:
    properties:
      role:
        type: string
      token:
        type: string
    type: object
  modular-monolith_internal_shared_response.APIResponse:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample API for a Modular Monolith built with Go Fiber.
  title: Modular Monolith API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT token
      parameters:
      - description: Login Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/modular-monolith_internal_modules_auth_domain.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/modular-monolith_internal_shared_response.APIResponse'
            - properties:
                data:
                  $ref: '#/definitions/modular-monolith_internal_modules_auth_domain.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/modular-monolith_internal_shared_response.APIResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/modular-monolith_internal_shared_response.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/modular-monolith_internal_shared_response.APIResponse'
      summary: User Login
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
